
project = DaoMake::Project( "DaoTestBase" )

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

project.UseImportLibrary( daovm )
project.SetTargetPath( "../../../lib/dao/modules/testing" )

project_objs = project.AddObjects( { "dao_test_base.c" } )
project_dll  = project.AddSharedLibrary( "dao_base", project_objs )
project_lib  = project.AddStaticLibrary( "dao_base", project_objs )

project.GenerateFinder( $TRUE );
project.Install( DaoMake::Variables[ "INSTALL_MOD" ], project_dll );
project.Install( DaoMake::Variables[ "INSTALL_MOD" ], project_lib );
