
project = DaoMake::Project( "DaoWeb" ) 

daovm = DaoMake::FindPackage( "Dao", $REQUIRED )

if( daovm == none ) return

project.AddDirectory( "http", "http" )
project.AddDirectory( "json", "json" )
project.AddDirectory( "cgi", "cgi" )
project.AddDirectory( "html", "html" )

project.UseImportLibrary( daovm, "dao" )
project.SetTargetPath( "../../lib/dao/modules/web" )

path = DaoMake::MakePath( DaoMake::Variables[ "INSTALL_MOD" ], "web" )

